// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuovmflglbqthnkwzphp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1b3ZtZmxnbGJxdGhua3d6cGhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NzkzMTAsImV4cCI6MjA3MzA1NTMxMH0.FP_nviSV3CLMfktAOKCSZBFlmYErwIBYww0neExQV9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});